# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-30 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('dishwashing', 'Dishwashing'), ('laundry', 'Laundry'), ('cleaning', 'Cleaning'), ('disinfection', 'Disinfection'), ('body care', 'Body Care'), ('other', 'Other')], default='', max_length=15),
        ),
    ]
